.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RESQUE\-POOL" "1" "June 2012" "RESQUE-POOL 0.4.0.DEV" "RESQUE-POOL"
.
.SH "NAME"
\fBresque\-pool\fR \- resque worker pool management
.
.SH "SYNOPSIS"
\fBresque\-pool\fR \fIoptions\fR
.
.SH "DESCRIPTION"
\fBResque\-pool\fR is the best way to manage a group (pool) of resque workers\.
.
.P
When resque\-pool(1) is daemonized the \fBstdout\fR and \fBstderr\fR output streams are redirected to \fBresque\-pool\.stdxxx\.log\fR log files in the \fBlog\fR directory\. Additionally the PID file defaults to \fBresque\-pool\.pid\fR in the \fBtmp/pids\fR directory\.
.
.SH "OPTIONS"
.
.IP "\(bu" 4
\fB\-c, \-\-config\fR \fIfile\fR: Uses the configuration specified in the \fIfile\fR provided instead of searching in the current and \fBconfig\fR directories for \fBresque\-pool\.yml\fR\.
.
.IP "\(bu" 4
\fB\-a, \-\-appname\fR \fIname\fR: Specifies the app name to be used for logging and procline\. If not specified, this defaults to the current working directory\.
.
.IP "\(bu" 4
\fB\-d, \-\-daemon\fR: Runs \fBresque\-pool\fR in the background as a daemon process\. This will redirect \fBstdout\fR and \fBstderr\fR to log files and write a PID file\.
.
.IP "\(bu" 4
\fB\-o, \-\-stdout\fR \fIfile\fR: Writes the normal log output to \fIfile\fR instead of printing to the terminal\. When running as a daemon this defaults to the path \fBlog/resque\-pool\.stdout\.log\fR\.
.
.IP "\(bu" 4
\fB\-e, \-\-stderr\fR \fIfile\fR: Writes the standard error output to \fIfile\fR instead of printing to the terminal\. When running as a daemon this defaults to the path \fBlog/resque\-pool\.stderr\.log\fR\.
.
.IP "\(bu" 4
\fB\-\-nosync\fR Allows writes to \fBstdout\fR and \fBstderr\fR to be buffered\.
.
.IP "\(bu" 4
\fB\-p, \-\-pidfile\fR \fIfile\fR: Writes the PID to the \fIfile\fR\. When running as a daemon this defaults to \fBtmp/pids/resque\-pool\.pid\fR\.
.
.IP "\(bu" 4
\fB\-E, \-\-environment\fR \fIname\fR: Specifies the environment \fIname\fR to be set for \fBRAILS_ENV\fR, \fBRACK_ENV\fR and \fBRESQUE_ENV\fR which will be passed on to the pooled resque workers\.
.
.IP "\(bu" 4
\fB\-\-term\-graceful\-wait\fR: Configure TERM signal handling so the master will gracefully request worker shut downs (via \fBQUIT\fR) and wait for the workers to quit before shutting down itself\. This is the same behavior as the \fBQUIT\fR signal\.
.
.IP "\(bu" 4
\fB\-\-term\-graceful\fR: Configure TERM signal handling so the master will gracefully request worker shut downs (via \fBQUIT\fR) but shut itself down immediately\. This the same behavior as the \fBINT\fR signal\.
.
.IP "\(bu" 4
\fB\-\-term\-immediate\fR: Configure TERM signal handling so the master will request imediate worker shut downs (via \fBINT\fR) and shut itself down immediately\. This is the default \fBTERM\fR signal behavior\.
.
.IP "" 0
.
.SH "HISTORY"
.
.TP
\fBv0\.3\.0\fR
Support for ruby 1\.9, resque 1\.20\.
.
.br
Added appname for logging\.
.
.br
Minor bugfixes\.
.
.TP
\fBv0\.2\.0\fR
Support for reloading logs and workers with \fBHUP\fR signal
.
.br
Cleans up PID file on startup
.
.br
Fixed \fB\-c, \-\-config\fR option\.
.
.TP
\fBv0\.1\.0\fR
\fBresque\-pool\fR command line interface added
.
.SH "AUTHOR"
Nicholas Evans
.
.SH "COPYRIGHT"
Copyright (C) 2010 by Nicholas Evans \fInick@ekenosen\.net\fR, et al\.
.
.SH "SEE ALSO"
resque\-pool\.yml(5)
